package com.rajatt7z.retailx.fragments.orders

import android.app.Dialog
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.LinearLayout
import android.widget.TextView
import androidx.fragment.app.DialogFragment
import com.rajatt7z.retailx.R
import com.rajatt7z.retailx.models.Bill
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class BillPreviewDialog(
    private val bill: Bill,
    private val onGenerateClick: () -> Unit // Optional if we want generate button inside dialog
) : DialogFragment() {

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.dialog_bill_preview, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        
        // Setup Header
        val tvDate = view.findViewById<TextView>(R.id.tvDate)
        val tvCustomer = view.findViewById<TextView>(R.id.tvCustomerName)
        val tvEmployee = view.findViewById<TextView>(R.id.tvEmployeeName)
        
        val sdf = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())
        tvDate.text = "Date: ${sdf.format(Date(bill.timestamp))}"
        tvCustomer.text = "Customer: ${bill.customerName} (${bill.customerPhone})"
        tvEmployee.text = "Generated By: ${bill.generatedByName}"

        // Setup Items
        val itemsContainer = view.findViewById<LinearLayout>(R.id.llItemsContainer)
        val inflater = LayoutInflater.from(context)
        
        bill.products.forEach { item ->
            val itemView = inflater.inflate(R.layout.item_preview_line, itemsContainer, false)
            
            itemView.findViewById<TextView>(R.id.tvItemName).text = item.productName
            itemView.findViewById<TextView>(R.id.tvItemPrice).text = String.format("$%.2f", item.unitPrice)
            itemView.findViewById<TextView>(R.id.tvItemQty).text = item.quantity.toString()
            itemView.findViewById<TextView>(R.id.tvItemTotal).text = String.format("$%.2f", item.totalPrice)
            
            itemsContainer.addView(itemView)
        }

        // Setup Total
        view.findViewById<TextView>(R.id.tvGrandTotal).text = String.format("$%.2f", bill.totalAmount)

        // Close Button
        view.findViewById<View>(R.id.btnClose).setOnClickListener {
            dismiss()
        }
    }

    override fun onStart() {
        super.onStart()
        dialog?.window?.setLayout(
            ViewGroup.LayoutParams.MATCH_PARENT, 
            ViewGroup.LayoutParams.WRAP_CONTENT
        )
    }
}
